apiVersion: v1
kind: Service
metadata:
  name: {{ include "actions-test.fullname" . }}
  labels:
    {{- include "actions-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "actions-test.selectorLabels" . | nindent 4 }}

# targetPort: is the port the container accepts traffic on, 
# port: is the abstracted Service port, which can be any port other pods use to access the Service
